"""
StadiumOps AI — Single-Venue Simulation Tool.

Reads matchday data from data/seed.json, sends it to the running FastAPI service,
and prints the resulting ranked decision engine recommendations and playbooks.
"""

import json
import os
import sys
import asyncio

# Configure stdout to output UTF-8 (fixes UnicodeEncodeError on Windows)
if hasattr(sys.stdout, "reconfigure"):
    sys.stdout.reconfigure(encoding="utf-8")

# Ensure project root is in the path
sys.path.append(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

import httpx

API_URL = "http://127.0.0.1:8000/api/analyze"
PLAYBOOK_URL = "http://127.0.0.1:8000/api/genai/playbook"
SEED_PATH = os.path.join(os.path.dirname(__file__), "seed.json")


async def run_simulation():
    if not os.path.exists(SEED_PATH):
        print(f"Error: Seed file not found at {SEED_PATH}")
        sys.exit(1)

    with open(SEED_PATH, "r", encoding="utf-8") as f:
        payload = json.load(f)

    print("=" * 80)
    print("STADIUMLOPS AI — SINGLE-VENUE MATCHDAY SIMULATOR")
    print("=" * 80)
    print(f"Loading seed data from: {SEED_PATH}")
    print(f"Active Incident: {payload['incident']['type']} in Zone {payload['incident']['zone']}")
    print(f"Weather: Temp {payload['weather']['temperature_celsius']}°C, Heat Index {payload['weather']['heat_index']}°C")
    print(f"Match Phase: {payload['event_context']['phase'].upper()}")
    print("-" * 80)

    async with httpx.AsyncClient() as client:
        try:
            # 1. Analyze and get recommendations
            print("Sending payload to /api/analyze...")
            response = await client.post(API_URL, json=payload, timeout=10.0)
            response.raise_for_status()
            data = response.json()

            print("\n[RECOMMENDATIONS GENERATED BY DECISION ENGINE]")
            for idx, rec in enumerate(data.get("recommendations", []), 1):
                print(f"{idx}. [{rec['severity'].upper()}] (Rule: {rec['rule_id']}) in Zone {rec['affected_zone']}")
                print(f"   Action: {rec['action']}")
                print(f"   Reason: {rec['reason']}")
                print(f"   Confidence: {rec['confidence']}\n")

            # 2. Generate playbook via GenAI
            print("Sending payload to /api/genai/playbook...")
            playbook_res = await client.post(PLAYBOOK_URL, json=payload, timeout=10.0)
            playbook_res.raise_for_status()
            playbook_data = playbook_res.json()

            print("\n[DOCK CONTROL ROOM TACTICAL BRIEFING (GENAI)]")
            print(f"Summary: {playbook_data.get('summary')}\n")
            print("Action Steps:")
            for step in playbook_data.get("steps", []):
                print(f"  - {step}")

            print("\nMultilingual Public Address Announcements:")
            announcements = playbook_data.get("announcements", {})
            for lang, ann in announcements.items():
                print(f"  [{lang.upper()}]: {ann}")

        except httpx.ConnectError:
            print("\n[CONNECTION ERROR] Could not connect to StadiumOps API server.")
            print("Please ensure the FastAPI server is running locally.")
            print("Run: uvicorn backend.api.main:app --reload")
            print("\nFalling back to direct local decision engine execution...")

            # Direct fallback
            from backend.core.decision_engine import (
                gate_load_balance,
                triage_incident,
                weather_action,
                accessibility_routing,
                egress_plan,
            )
            from backend.models.schemas import (
                AnalyzeRequest,
            )

            # Validate input locally using Pydantic
            req = AnalyzeRequest(**payload)

            recs = []
            recs.extend(gate_load_balance(req.gates))
            recs.append(triage_incident(req.incident))
            recs.extend(weather_action(req.weather))
            recs.extend(accessibility_routing(req.event_context, req.incident))
            recs.extend(egress_plan(req.event_context, req.gates))

            recs.sort(key=lambda r: {"Critical": 0, "High": 1, "Medium": 2, "Low": 3}.get(r.severity.value, 99))

            print("\n[RECOMMENDATIONS (LOCAL FALLBACK ENGINE)]")
            for idx, r in enumerate(recs, 1):
                print(f"{idx}. [{r.severity.value.upper()}] (Rule: {r.rule_id}) in Zone {r.affected_zone}")
                print(f"   Action: {r.action}")
                print(f"   Reason: {r.reason}")
                print(f"   Confidence: {r.confidence.value}\n")

    print("=" * 80)
    print("SIMULATION END")
    print("=" * 80)


if __name__ == "__main__":
    asyncio.run(run_simulation())
